server:
  port: "${port:8110}"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    com.gk.mortgage.calculator: INFO
    
spring:
  application:
    name: mortgage-calculator
  security:
    user:
      name: user1
      password: password1
      roles: api-user

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  # metrics:
  #   tags:
  #     application: ${spring.application.name}
    
environment:
  interestrate:
    uri: ${INTEREST_RATE_SERVICE_URI:http://localhost:8111/interest-rates}
    username: user1
    password: password1
  persistRequestDataToDB: ${PERSIST_REQUEST_DATA_TO_DB:false}
  dynamoDBTable: ${DYNAMO_DB_TABLE:mortgage-calculator-dev}