server:
  port: "${port:8110}"

logging:
  level:
    root: INFO
    com.gk.mortgage.calculator: INFO
    
spring:
  application:
    name: mortgage-calculator
  sleuth:
     trace-id128: true
  security:
    user:
      name: user1
      password: password1
      roles: api-user

management:
  security:
    enabled: false
    
environment:
  interestrate:
    uri: ${INTEREST_RATE_SERVICE_URI:http://localhost:8111/interest-rates}
    username: user1
    password: password1