apiVersion: v1
kind: ConfigMap
metadata:
  name: mortgage-calculator
  namespace: mc-dev
data:
  PERSIST_REQUEST_DATA_TO_DB: "false"
  INTEREST_RATE_SERVICE_URI: interest-rate
  ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
  DYNAMO_DB_TABLE: mortgage-calculator-dev