name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - run: mkdir staging && cp target/*.jar staging
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}"
          push: true
          tags: gkovan/mortgage-calculator-github-action:latest      
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: target
  push_to_registry:
    needs: build
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Package
          path: target        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: gkovan/mmortgage-calculator-github-action:latest
  testDev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test dev environment
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: ./postman/thunder-collection_MortgageCalculator_postman.json
          environment: ./postman/thunder-environment_mortgage-calculator-apigw-mock_postman.json
          reporters: cli
      - name: Output summary to console
        run: echo ${{ steps.run-newman.outputs.summary }}        

  testDev2:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Isstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      # Install Thunder Client CLI
      - name: Install Thunder Client CLI
        run: |
          npm install -g @thunderclient/cli
          
      - name: Make Directory for results
        run: mkdir -p thunder-reports

      # Run the Thunder Client collection
      - name: Run Thunder Client collection
        run: |
          tc --fol "./thunder" --col "MortgageCalculator" --env 'mortgage-calculator-apigw-mock' --report csv,json,xml,html
      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: thunder-reports

